import Head from 'next/head'
import { Inter } from '@next/font/google'
import PageLayout from '../components/PageLayout'
import { Box, Card, Grid, Link, Toolbar, Typography } from '@mui/material'
import { MdWarning } from 'react-icons/md'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Carly</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/ColoredLogo.svg" />
      </Head>
      <main>
        <PageLayout
          hideDrawer
        >
          <Grid
            container
            sx={{ height: "100%", width: "100%", pb: 20 }}
            alignItems="center"
            justifyContent="center"
          >
            <Grid item xs={4} />
            <Grid item xs={4}>
              <Card>
                <Grid
                  container
                  direction="column"
                  gap={1}
                  alignItems="center"
                  justifyContent="center"
                  sx={{ p: 2 }}
                >
                  <Grid item>
                    <MdWarning color="orange" size={50} />
                  </Grid>
                  <Grid item>
                    <Typography variant="h5">
                      Page not found
                    </Typography>
                  </Grid>
                  <Grid item>
                    <Link href="#" onClick={() => router.back()}>Go back</Link>
                  </Grid>
                </Grid>
              </Card>
            </Grid>
            <Grid item xs={4} />
          </Grid>
        </PageLayout>
      </main>
    </>
  )
}
