import Head from 'next/head'
import PageLayout from '../components/PageLayout'
import Image from "next/image";
import { Grid, Typography } from "@mui/material";
import { useEffect } from 'react';
import { useJwtToken } from '../functions/useJwtToken';

export default function Home() {
  const token = useJwtToken();
  
  // Bad workaround.
  useEffect(() => {
    fetch('https://carlybackend.azurewebsites.net/cars', {
        method: 'GET',
        headers: {
          'Authorization': `Bearer ${token}`
        }})
  }, []);

  return (
    <>
      <Head>
        <title>Carly</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/ColoredLogo.svg" />
      </Head>
      <main>
        <PageLayout>
          <div>
            <Grid container alignItems="center"
              justifyContent="center">
              <Grid item xs={12} sx={{ mt: 8 }}>
                <Typography sx={{ textAlign: 'center' }} variant="h3" gutterBottom>
                  WELCOME BACK
                </Typography>
              </Grid>
              <Grid item>
                <Image src="/ColoredLogo.svg" alt="Carly" width={500} height={300} />
              </Grid>
            </Grid>

          </div>
        </PageLayout>
      </main>
    </>
  )
}
