import Head from 'next/head'
import PageLayout from '../components/PageLayout'

export default function Settings() {
  return (
    <>
      <Head>
        <title>Carly</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/ColoredLogo.svg" />
      </Head>
      <main>
        <PageLayout>
          <div>
            <p>
              Content
            </p>
          </div>
        </PageLayout>
      </main>
    </>
  )
}
